### ISSUE TITLE
ROR KANBAN BOARD

### ISSUE THREAD

**Issue by altontonn** [altontonn/Recipe-app#9]
# Recipe App 💎
In this Ruby Group Project, our team is comprised of two members: 

- [Newton](https://github.com/altontonn)
- [Raphael](https://github.com/eerapheal)

The link to the project 👉 [Recipe-app](https://github.com/altontonn/Recipe-app)

**Comment by Whoistolu** [comment]
### Hi Team,
@altontonn and @eerapheal 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

### Highlight
✔️ Tasks are distributed in a fair way
✔️ Link to GitHub project is present
✔️ Information about the number of people in their group is provided

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
